/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "secondary": "#0058be",
              "surface-container": "#edeef0",
              "primary-fixed-dim": "#bec6e0",
              "on-error-container": "#93000a",
              "on-tertiary": "#ffffff",
              "error": "#ba1a1a",
              "on-error": "#ffffff",
              "on-tertiary-container": "#009668",
              "tertiary-fixed-dim": "#4edea3",
              "primary-fixed": "#dae2fd",
              "on-secondary-fixed-variant": "#004395",
              "surface-container-highest": "#e1e2e4",
              "on-surface": "#191c1e",
              "surface-container-lowest": "#ffffff",
              "surface-tint": "#565e74",
              "on-primary": "#ffffff",
              "surface-container-high": "#e7e8ea",
              "surface-dim": "#d9dadc",
              "background": "#f8f9fb",
              "on-secondary": "#ffffff",
              "surface-bright": "#f8f9fb",
              "surface": "#f8f9fb",
              "inverse-surface": "#2e3132",
              "on-secondary-fixed": "#001a42",
              "on-surface-variant": "#45464d",
              "primary-container": "#131b2e",
              "primary": "#000000",
              "secondary-container": "#2170e4",
              "on-tertiary-fixed": "#002113",
              "error-container": "#ffdad6",
              "surface-container-low": "#f3f4f6",
              "surface-variant": "#e1e2e4",
              "inverse-on-surface": "#f0f1f3",
              "on-primary-fixed": "#131b2e",
              "secondary-fixed-dim": "#adc6ff",
              "tertiary-container": "#002113",
              "on-tertiary-fixed-variant": "#005236",
              "secondary-fixed": "#d8e2ff",
              "inverse-primary": "#bec6e0",
              "outline-variant": "#c6c6cd",
              "on-background": "#191c1e",
              "outline": "#76777d",
              "on-primary-container": "#7c839b",
              "tertiary-fixed": "#6ffbbe",
              "on-primary-fixed-variant": "#3f465c",
              "tertiary": "#000000",
              "on-secondary-container": "#fefcff"
          },
          borderRadius: {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          spacing: {
              "base": "8px",
              "lg": "24px",
              "xs": "4px",
              "margin": "24px",
              "xl": "32px",
              "gutter": "16px",
              "md": "16px",
              "sm": "8px"
          },
          fontFamily: {
              "data-mono": ["IBM Plex Mono", "monospace"],
              "headline-md": ["Plus Jakarta Sans", "sans-serif"],
              "body-md": ["Plus Jakarta Sans", "sans-serif"],
              "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
              "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
              "body-lg": ["Plus Jakarta Sans", "sans-serif"],
              "label-caps": ["Plus Jakarta Sans", "sans-serif"],
              "body-sm": ["Plus Jakarta Sans", "sans-serif"]
          },
          fontSize: {
              "data-mono": ["13px", { "lineHeight": "16px", "fontWeight": "500" }],
              "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
              "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
              "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
              "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
              "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
              "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }]
          }
      }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
